# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - build
    - -f
    - ./Dockerfile-kubepkg
    - --tag=$_REGISTRY/kubepkg:$_GIT_TAG
    - --tag=$_REGISTRY/kubepkg:latest
    - .
  - name: gcr.io/cloud-builders/docker
    args:
    - build
    - -f
    - ./Dockerfile-kubepkg-rpm
    - --tag=$_REGISTRY/kubepkg-rpm:$_GIT_TAG
    - --tag=$_REGISTRY/kubepkg-rpm:latest
    - .
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
  _REGISTRY: 'fake.repository/registry-name'
  # TODO(images): Remove once CI failures are resolved.
  _CI_FAILURES: 'https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-kubepkg/1382830189301469184'
images:
  - 'gcr.io/$PROJECT_ID/kubepkg:$_GIT_TAG'
  - 'gcr.io/$PROJECT_ID/kubepkg:latest'
  - 'gcr.io/$PROJECT_ID/kubepkg-rpm:$_GIT_TAG'
  - 'gcr.io/$PROJECT_ID/kubepkg-rpm:latest'
