# See https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md for more details on image pushing process

# this must be specified in seconds. If omitted, defaults to 600s (10 mins)
timeout: 1200s
# this prevents errors if you don't use both _GIT_TAG and _PULL_BASE_REF,
# or any new substitutions added in the future.
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20201130-750d12f'
    entrypoint: 'bash'
    dir: ./cmd/vulndash
    env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - REGISTRY=gcr.io/$PROJECT_ID
    - HOME=/root
    - TAG=$_GIT_TAG
    - PULL_BASE_REF=$_PULL_BASE_REF
    - IMAGE_VERSION=$_IMAGE_VERSION
    - GO_VERSION=$_GO_VERSION
    - DISTROLESS_IMAGE=$_DISTROLESS_IMAGE
    args:
    - '-c'
    - |
      gcloud auth configure-docker \
      && make manifest

substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
  _IMAGE_VERSION: 'v0.0.0'
  _GO_VERSION: '0.0.0'
  _DISTROLESS_IMAGE: 'static-debian00'

tags:
- 'vulndash'
- ${_GIT_TAG}
- ${_PULL_BASE_REF}
- ${_IMAGE_VERSION}
- ${_GO_VERSION}
- ${_DISTROLESS_IMAGE}

images:
  - 'gcr.io/$PROJECT_ID/vulndash-amd64:$_IMAGE_VERSION'
  - 'gcr.io/$PROJECT_ID/vulndash-amd64:$_GIT_TAG'
  - 'gcr.io/$PROJECT_ID/vulndash-amd64:latest'
